services:
  hackathon.api:
    image: hackathon.api
    build:
      context: .
      dockerfile: Hackathon.API/Dockerfile
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "TinkoffQnA"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Hackathon2024"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    